version: '3'

vars:
  DOCKER_IMAGE: my-prompts-mcp-dev
  DOCKER_RUN_PARAMS: --rm -v $(pwd):/app --user $(id -u):$(id -g)
  DOCKER_RUN: run {{.DOCKER_RUN_PARAMS}} {{.DOCKER_IMAGE}}

tasks:
  default: task --list

  build-phar:
    desc: Build PHAR archive
    cmd: docker {{.DOCKER_RUN}} box compile

  build-binary:
    desc: Build binary file
    cmds:
      - docker {{.DOCKER_RUN}} box compile
      - mkdir -p runtime/static-php-cli
      - docker run {{.DOCKER_RUN_PARAMS}} --workdir=/app/runtime/static-php-cli {{.DOCKER_IMAGE}}
          spc micro:combine
            --with-micro=/builder/buildroot/bin/micro.sfx
            --output=/app/build/my-prompts-mcp
            /app/build/my-prompts-mcp.phar

  build-docker-image:
    desc: Build Docker image
    cmd: docker build -t {{.DOCKER_IMAGE}} .

  docker-shell:
    desc: Run Docker shell
    cmd: docker run {{.DOCKER_RUN_PARAMS}} -it {{.DOCKER_IMAGE}} sh

  lint-dockerfile:
    desc: Lint Dockerfile
    cmd: docker run --rm -i hadolint/hadolint < Dockerfile

  cs-fix:
    desc: Run PHP CS Fixer
    cmd: docker {{.DOCKER_RUN}} vendor/bin/php-cs-fixer fix

  composer:
    desc: Run Composer command
    cmd: docker {{.DOCKER_RUN}} composer {{.CLI_ARGS}}
