version: '3'

vars:
  DOCKER_IMAGE: my-prompts-mcp

tasks:
  default: task --list

  build-phar:
    desc: Build PHAR archive
    cmd: docker run --rm -v $(pwd):/app --user $(id -u):$(id -g) {{.DOCKER_IMAGE}} box compile

  build-binary:
    desc: Build binary file
    cmds:
      - task: build-phar
      - cmd: docker run --rm -v $(pwd):/app --user $(id -u):$(id -g) {{.DOCKER_IMAGE}}
          spc micro:combine
            --with-micro=/builder/buildroot/bin/micro.sfx
            --output=/app/build/my-prompts-mcp
            /app/build/my-prompts-mcp.phar

  build-docker-image:
    desc: Build Docker image
    cmd: docker build -t {{.DOCKER_IMAGE}} .

  composer:
    desc: Run Composer command
    cmd: docker run --rm -v $(pwd):/app --user $(id -u):$(id -g) {{.DOCKER_IMAGE}} composer {{.CLI_ARGS}}
